"""Weekly portfolio health synthesis.

One-shot script meant to be run after the Friday matrix tick. Stitches
together:

  1. portfolio_load_context  — book + matrix join + flags
  2. portfolio_allocation    — exposure / breaches / cash buffer
  3. portfolio_trade_tickets — sorted action queue including new picks

Writes the markdown synthesis to stdout (and optionally to a file).
Designed to be the canonical "what changed this week and what should I do"
artifact you re-read each weekend.

Usage::

    # After Friday matrix run finishes
    .venv/bin/python scripts/portfolio_health.py

    # Save to a dated snapshot for diff-vs-last-week
    .venv/bin/python scripts/portfolio_health.py \\
        --output runs/portfolio/snapshots/2026-05-09.md
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.portfolio_allocation import build_report, render_markdown as render_alloc  # noqa: E402
from scripts.portfolio_load_context import (  # noqa: E402
    DEFAULT_POLICY,
    DEFAULT_POSITIONS,
    build_context,
    render_markdown as render_ctx,
)
from scripts.portfolio_trade_tickets import build_queue, render_tickets_markdown  # noqa: E402


def render_health(
    positions_path: Path = DEFAULT_POSITIONS,
    policy_path: Path = DEFAULT_POLICY,
    matrix_run_path: Path | None = None,
    include_new_picks: bool = True,
    max_new: int = 5,
) -> str:
    parts: list[str] = []
    today = date.today().isoformat()
    parts.append(f"# Portfolio health — {today}")
    parts.append("")
    parts.append(
        "_Generated by `scripts/portfolio_health.py`. "
        "Sections: Context · Allocation · Trade tickets._"
    )
    parts.append("")

    parts.append("---")
    parts.append("")
    ctx = build_context(positions_path, policy_path, matrix_run_path)
    parts.append(render_ctx(ctx))

    parts.append("")
    parts.append("---")
    parts.append("")
    alloc = build_report(positions_path, policy_path, matrix_run_path)
    parts.append(render_alloc(alloc))

    parts.append("")
    parts.append("---")
    parts.append("")
    queue = build_queue(
        positions_path,
        policy_path,
        matrix_run_path,
        include_new_picks=include_new_picks,
        max_new=max_new,
    )
    parts.append(render_tickets_markdown(queue["tickets"], queue["summary"]))

    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--positions-file", type=Path, default=DEFAULT_POSITIONS)
    parser.add_argument("--policy-file", type=Path, default=DEFAULT_POLICY)
    parser.add_argument("--matrix-run", type=Path, default=None)
    parser.add_argument("--no-new-picks", action="store_true",
                        help="Skip the 'new picks' section of the trade ticket queue")
    parser.add_argument("--max-new", type=int, default=5)
    parser.add_argument("--output", type=Path, default=None,
                        help="Write the report to this path (still echoed to stdout)")
    args = parser.parse_args(argv)

    text = render_health(
        args.positions_file,
        args.policy_file,
        args.matrix_run,
        include_new_picks=not args.no_new_picks,
        max_new=args.max_new,
    )
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
        print(f"\n# Saved to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
